# Generated by Django 4.2.1 on 2023-06-09 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320)),
                ('icons', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=320, verbose_name='Имя')),
                ('description', models.TextField(blank=True)),
                ('options', models.JSONField()),
                ('categori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.file')),
            ],
        ),
    ]
